### PR TITLE
Fix for Anchorites Flight

### PR DESCRIPTION
**Pull request by Aspurgus**
uses compound tag instead of long array for fetching flight origin

### CODE REVIEW

**Comment by XieDeWu** [comment]
Finally repaired

**Comment by object-Object** [comment]
@Aspurgus Sorry for the delay on this. Would you be able to rebase your PR branch onto `main` to get rid of that extra commit? (Alternatively, just opening a new PR based on main might be simpler.)

**Comment by Aspurgus** [comment]
Made a new pr for the main [here](https://github.com/FallingColors/HexMod/pull/684)

**Comment by object-Object** [comment]
thanks!

**Pull request closed without merging**
