### PR TITLE
Add new ru_ru localization

### PR DESCRIPTION
**Pull request by GrinNik**

### CODE REVIEW

**Comment by object-Object** [comment]
Thanks!

**Comment by GrinNik** [comment]
I'll try to make it better when I see it in the game.

**Comment by object-Object** [comment]
The web book is updated now: https://hexcasting.hexxy.media/v/latest/main/ru_ru/

**Comment by GrinNik** [comment]
@object-Object Is that my translation or someone else's?

**Comment by LedinecMing** [comment]
This needs serious improvements, I am working on it right now.

**Pull request merged**
