### PR TITLE
add localization entry for location_too_far

### PR DESCRIPTION
**Pull request by navarchus**
address #649 (Tested, works on fabric)

### CODE REVIEW

**Comment by object-Object** [comment]
oh, huh.

https://github.com/FallingColors/HexMod/blob/b4aa31996bd0983135e4b949f30d2f24f4fd2f04/Common/src/main/resources/assets/hexcasting/lang/en_us.flatten.json5#L958-L964

https://github.com/FallingColors/HexMod/blob/b4aa31996bd0983135e4b949f30d2f24f4fd2f04/Common/src/main/java/at/petrak/hexcasting/api/casting/mishaps/MishapBadLocation.kt#L19-L21

So the actual bug is that the keys in the file are eg. `hexcasting.mishap.location.too_far` (with a period), but the mishap is constructing keys like `hexcasting.mishap.location_too_far` (with an underscore).

On 1.19, these keys used an underscore, so I think the best fix would be to update the file to match.

We should be able to do that just by changing this line from `location: {` to `"location_": {` .

https://github.com/FallingColors/HexMod/blob/b4aa31996bd0983135e4b949f30d2f24f4fd2f04/Common/src/main/resources/assets/hexcasting/lang/en_us.flatten.json5#L958

**Comment by navarchus** [comment]
yep that works lol

**Comment by object-Object** [comment]
cool cool
actually, I guess we may as well also update the other lang files (zh_cn, ru_ru) with the same change if you can? I should have mentioned it before, sorry

**Comment by object-Object** [comment]
lmfao thanks

**Pull request merged**
