### PR TITLE
Add option to have click toggle drawing instead of dragging

### LINKED ISSUE #357: client config option Click type option ->"click (start) then click(end)" rather than "click hold(start + continue) then release(end)" client config option?
is there a plan ever to add a local config to do spells via "click (start) then click(end)" rather than "click hold(start + continue)  then release(end)"

For accessibility for those who don't want to hold click for patterns (especially longer ones) & release click still there for those who want less clicks.

### PR DESCRIPTION
**Pull request by vgskye**
closes #357. confirmed working on fabric, forge should probably work

### CODE REVIEW

**Comment by vgskye** [comment]
tested and working on forge as well

**Comment by object-Object** [comment]
We should probably also add a localization to the lang file for this cloth config entry. see here:

https://github.com/FallingColors/HexMod/blob/f3f9d0740bda6df22826c18780e0241500983e6b/Common/src/main/resources/assets/hexcasting/lang/en_us.flatten.json5#L286-L303

**Comment by vgskye** [comment]
> We should probably also add a localization to the lang file for this cloth config entry.
I feel like this can be batched with #729?

**Comment by object-Object** [comment]
i don't see any reason to? just because other options didn't get localizations doesn't mean we should continue not adding them for new ones. imo the localizations for a given feature should be added in the PR where the feature itself is added when possible.

**Comment by vgskye** [comment]
fair, lemme add that after a rebase

**Comment by gamma-delta** [comment]
If it's tested and confirmed working it LGTM.

**Review by gamma-delta — APPROVED** [review]
Yep, LGTM

**Comment by vgskye** [comment]
why the fuck is hexdoc failing I didn't even touch anything doc-related

**Comment by gamma-delta** [comment]
The hexdoc issue was fixed https://github.com/hexdoc-dev/hexdoc/commit/9e1025c13a1f552d34cd7885471edb34fb821e63 so hopefully that should pass now

**Comment by gamma-delta** [comment]
We *should* probably document this at some point but again not something I care to block on.

**Pull request merged**
