### PR TITLE
make circles have ambit on player again

### LINKED ISSUE #591: [1.20] Bound cleric circle doesn't have ambit at bound player
**Version used: 0.11.1, build 609**

In previous versions, a bound cleric circle would always have access to the bound player along with a small radius around them. In 1.20, this does not seem to be the case. A bound cleric circle that attempts to use Mind's Reflection will fail unless the bound player is standing in the circle.

### PR DESCRIPTION
**Pull request by walksanatora**
closes #591

### CODE REVIEW

**Comment by walksanatora** [comment]
also closes #561

**Comment by Talia-12** [comment]
As I recall in previous versions the circle ambit around a player was PLAYER_HEIGHT rather than 32?

**Comment by walksanatora** [comment]
ah right I forgot about that

**Comment by Talia-12** [comment]
Ended up making a separate PR to fix the ambit range issue

**Pull request closed without merging**
