### PR TITLE
Document Media Cube

### LINKED ISSUE #390: Hidden debug cube features should be documented somewhere
Currently, as far as I know, to find out about the debug cube features (eg. "debug media") you need to actually look at the code. I think there should be a table in the notebook listing them, maybe locked behind a hidden advancement granted by obtaining the media cube.

### PR DESCRIPTION
**Pull request by navarchus**
Fixes #390 
Add hidden entry in book gated by advancement. Explains function of Media Cube once it has been put into Player's inventory.

### CODE REVIEW

**Comment by object-Object** [comment]
something seems messed up with the commits - there are some commits on this branch that are also on `main` but with a different SHA.

**Comment by navarchus** [comment]
> something seems messed up with the commits - there are some commits on this branch that are also on `main` but with a different SHA.

I did a force push to revert an unnecessary commit, should I just open a new PR

**Comment by object-Object** [comment]
you can if you want, or you could fix it with rebase, or I can probably fix it if I get a chance

**Comment by navarchus** [comment]
> you can if you want, or you could fix it with rebase, or I can probably fix it if I get a chance

I'll give it a shot tomorrow

**Comment by gamma-delta** [comment]
I feel like if we're documenting the media cube we should probably document the stuff it *does* (does it still have the thing where it displays all the patterns executed based on the anvil rename?)

**Comment by object-Object** [comment]
`debug patterns` still works, but `debug media` doesn't (#640)

**Comment by gamma-delta** [comment]
Again this is something I'd rather not block the release on. Hexdebug is a way better debugger anyways.

**Comment by object-Object** [comment]
mmm, yeah. the point of #390 was specifically to document those hidden features accessible by renaming the item.

**Comment by navarchus** [comment]
I can take a second pass at this and redo the documentation sometime this week if that's necessary.

**Pull request closed without merging**
